#!/bin/bash

set -e

# Get the directory where the program is installed
SCRIPT_DIR="/home/user/example-of-debian-package/my-program"

# Make the program executable
chmod +x $SCRIPT_DIR/main.py

# Create a symlink to make the program available system-wide
ln -s $SCRIPT_DIR/main.py /usr/local/bin/my_program

# Add an alias for the program to the user's bashrc
echo "alias my_program='python3 /usr/local/bin/my_program'" >> ~/.bashrc
source ~/.bashrc
